### ISSUE TITLE
2 Instances of MainActivity

### ISSUE THREAD

**Issue by JaeW** [dynamite8/resources-android-dev#133]
After navigating through app and returning to the home MainActivity, if the back button is pushed one instance of MainActivity is destroyed, but another is sitting behind it.  Two taps of the back button are required to exit the app.

**Comment by JaeW** [comment]
In LaunchActivity in the method, startMainActivity() after creating the intent to launch MainActivity.class, add this line:
intent.addFlags(Intent.FLAG_ACTIVITY_REORDER_TO_FRONT);

**Comment by dynamite8** [comment]
@JaeW the part about 2 taps of the back button, that's the requirement or how it works generally on android apps.  Are you indicating that this is a bug?

**Comment by JaeW** [comment]
@dynamite8 Once a user is on the main or launch screen (as registered in the manifest), it requires 2 taps of the back button to exit the app.  You can actually see one instance of the MainActivity close with another still behind it.  This is not normal Android behavior.

**Comment by dambadipudi** [comment]
What is going on in the app is that two instances of MainActivity are being created - one in onCreate() method, and one in onResume() method(this snippet was added by Olga in order to handle network interruptions). Although at that time it seemed a good way to handle the interruption, it now results in two activities being created. Would a better way to handle network interruptions be to create a toast if there is an exception and letting the user know?
